### PR TITLE
fix: rename red palette to magenta and add true red palette

### LINKED ISSUE #602: Change the `red` palette to `magenta` and add a generic `red` palette
#### Current Behavior

The `red` palette is actually a range of hues in the red-purplish angling towards more pinkish and purplish. 

Need a new `red` palette that specific to the `red` color. Can use `#F91313`, which is being used for the notification error as the starter color.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
  - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Sistent site](https://www.figma.com/file/ekm0Hh6M25bSKpP5BcIJom/Sistent-Design-System?type=design&node-id=596%3A5227&mode=design&t=8MExPykHN1vQFCTZ-1) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by jeetburman**
This PR addresses issue #602 by renaming the existing red palette to magenta and introducing a new true red palette.

- Renamed existing red palette to magenta (pinkish-red hues)
- Created new red palette based on #F91313 (notification error color)
- Updated palette.ts to use magenta for error backgrounds
- New red palette provides true red colors for error states

Resolves #602

**Notes for Reviewers**

This PR fixes #602

The existing `red` palette contained pinkish-magenta hues (e.g., `#ff385c`, `#FFB3B9`). This has been renamed to `magenta` for semantic accuracy. A new `red` palette has been created using `#F91313` as the base color, which is already used for notification errors and provides true red colors.

Changes are backward compatible - the magenta palette retains all the previous red values, and components using error states now benefit from more accurate red colors.

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [x] Yes, I signed my commits.

### CODE REVIEW

File: src/theme/colors/colors.ts [hunk 1]
```diff
@@ -154,7 +154,7 @@ export const yellow = {
   10: '#663A00'
 };
 
-export const red = {
+export const magenta = {
```
Comment (saurabhraghuvanshii) [inline src/theme/colors/colors.ts:167]: I think these are shades of Rose Red than magenta

**Comment by jeetburman** [comment]
@saurabhraghuvanshii ,
I've updated the magenta palette to proper magenta (purple-pink) shades:
- `magenta[70]: #FFF0FA` (was #FFF0F0)
- `magenta[60]: #FFB3E6` (was #FFB3B9)
- `magenta[50]: #FF66CC` (was #FF6179)
- `magenta[40]: #E600AC` (was #ff385c) 
- `magenta[30]: #B30086` (was #B3153D)
- `magenta[20]: #800060` (was #8C0a2F)
- `magenta[10]: #4D0039` (was #660624)

The magenta palette now uses true purple-pink colors instead of rose-red. The `red` palette remains unchanged with true red colors based on #F91313.

**Comment by nebula-aac** [comment]
ack, reviewing now
